site_name: Dwarf Tales
site_url: https://dwarffortress.nwest.wiki/
repo_url: https://github.com/nwesterhausen/dwarf-tales
edit_uri: edit/main/docs
site_author: Nicholas Westerhausen
copyright: ©2020 Nick Westerhausen
theme:
  name: material
  palette:
    scheme: slate
    primary: brown
    accent: yellow
  font:
    text: Commissioner
    code: Roboto Mono
  icon:
    logo: material/pickaxe
    repo: fontawesome/brands/github-square
  custom_dir: overrides

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - img2fig
  - awesome-pages
  - navtitles
  - redirects:
      redirect_maps:
        "ushuldakon/ulingbomrek/index.md": "ushuldakon/ulingbomrek/embark.md"

markdown_extensions:
  - abbr
  - pymdownx.tabbed
  - pymdownx.snippets
